using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

namespace RichTextBlockCompat;

public static class ReportWriter
{
    public static void WriteMarkdown(IReadOnlyList<TypeCheckResult> results, MetadataLoader loader, string path)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# RichTextBlock API Parity with WinUI 3");
        sb.AppendLine();

        var grandTotal = results.Sum(r => r.Total);
        var grandMatched = results.Sum(r => r.Matched);
        var overallPct = grandTotal == 0 ? 100.0 : grandMatched * 100.0 / grandTotal;

        sb.AppendLine($"**Coverage: {overallPct:F1}%** ({grandMatched} / {grandTotal} WinUI 3 members)");
        sb.AppendLine();
        sb.AppendLine("**Goal:** 100% API parity with WinUI 3.");
        sb.AppendLine();
        sb.AppendLine($"- **Reference:** Microsoft.WinUI from the Windows App SDK ({GetWinAppSdkVersion(loader)}).");
        sb.AppendLine("- **Subject:** the LeXtudio types listed below — the union of `LeXtudio.UI.Xaml.Controls.RichTextBlock` and the `System.Windows.Documents.*` types in `LeXtudio.Windows`.");
        sb.AppendLine();

        sb.AppendLine("## Per-Type Summary");
        sb.AppendLine();
        sb.AppendLine("| Type | Coverage | Matched | Mismatched | Missing |");
        sb.AppendLine("|---|---:|---:|---:|---:|");
        foreach (var r in results)
        {
            sb.AppendLine($"| `{ShortName(r.WinUITypeName)}` | {r.Percentage:F1}% | {r.Matched} | {r.Mismatched} | {r.Missing} |");
        }
        sb.AppendLine();

        sb.AppendLine("## Gap by Member Kind");
        sb.AppendLine();
        sb.AppendLine("Where the work is concentrated. Each cell counts WinUI 3 members of that kind that are Missing or Mismatched on the subject side.");
        sb.AppendLine();
        sb.AppendLine("| Type | Property | Method | Event | DP Field |");
        sb.AppendLine("|---|---:|---:|---:|---:|");
        foreach (var r in results)
        {
            var g = r.GapsByKind();
            sb.AppendLine($"| `{ShortName(r.WinUITypeName)}` | {Get(g, MemberKind.Property)} | {Get(g, MemberKind.Method)} | {Get(g, MemberKind.Event)} | {Get(g, MemberKind.DependencyPropertyField)} |");
        }
        sb.AppendLine();

        foreach (var r in results)
        {
            sb.AppendLine($"## {ShortName(r.WinUITypeName)}");
            sb.AppendLine();
            sb.AppendLine($"- **WinUI 3:** `{r.WinUITypeName}`");
            sb.AppendLine($"- **Subject:** `{r.LocalTypeName}`");
            sb.AppendLine($"- **Coverage:** {r.Percentage:F1}% ({r.Matched}/{r.Total} WinUI 3 members)");
            sb.AppendLine();

            var gaps = r.Members
                .Where(m => m.Status != MatchStatus.Match)
                .OrderBy(m => m.Status)
                .ThenBy(m => m.Reference.Kind)
                .ThenBy(m => m.Reference.Name)
                .ToList();

            if (gaps.Count == 0)
            {
                sb.AppendLine("All WinUI 3 members are covered. :white_check_mark:");
                sb.AppendLine();
                continue;
            }

            sb.AppendLine("### Gaps");
            sb.AppendLine();
            sb.AppendLine("| Status | Kind | WinUI 3 signature | Subject signature |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var c in gaps)
            {
                var statusIcon = c.Status switch
                {
                    MatchStatus.Missing => ":x: Missing",
                    MatchStatus.SignatureMismatch => ":warning: Mismatch",
                    _ => "?",
                };
                var localSig = c.Found is null ? "—" : EscapeMd(c.Found.Signature);
                sb.AppendLine($"| {statusIcon} | {c.Reference.Kind} | `{EscapeMd(c.Reference.Signature)}` | `{localSig}` |");
            }
            sb.AppendLine();
        }

        sb.AppendLine("---");
        sb.AppendLine($"_Generated by `tools/RichTextBlockCompat`. Reference is real WinUI 3 metadata (Microsoft.WinUI.dll from Windows App SDK), loaded via System.Reflection.MetadataLoadContext. The check is unidirectional (WinUI → Subject); extra members on the subject side do not count as incompatibilities._");

        File.WriteAllText(path, sb.ToString());
    }

    public static void WriteConsoleSummary(IReadOnlyList<TypeCheckResult> results, MetadataLoader loader, string reportPath)
    {
        var grandTotal = results.Sum(r => r.Total);
        var grandMatched = results.Sum(r => r.Matched);
        var pct = grandTotal == 0 ? 100.0 : grandMatched * 100.0 / grandTotal;

        System.Console.WriteLine();
        System.Console.WriteLine($"RichTextBlock API Parity with WinUI 3  (WinAppSDK {GetWinAppSdkVersion(loader)})");
        System.Console.WriteLine("============================================================");
        foreach (var r in results)
        {
            System.Console.WriteLine($"  {r.Percentage,6:F1}%  {ShortName(r.WinUITypeName),-22} ({r.Matched}/{r.Total})");
        }
        System.Console.WriteLine("  --------");
        System.Console.WriteLine($"  {pct,6:F1}%  OVERALL                ({grandMatched}/{grandTotal})  TARGET: 100.0%");
        System.Console.WriteLine();
        System.Console.WriteLine($"Report written to: {reportPath}");
    }

    private static string ShortName(string fullName)
    {
        var i = fullName.LastIndexOf('.');
        return i < 0 ? fullName : fullName[(i + 1)..];
    }

    private static string EscapeMd(string s) => s.Replace("|", "\\|");

    private static int Get(Dictionary<MemberKind, int> dict, MemberKind k) =>
        dict.TryGetValue(k, out var v) ? v : 0;

    /// <summary>Reads the version from the loaded Microsoft.WinUI assembly for self-describing reports.</summary>
    private static string GetWinAppSdkVersion(MetadataLoader loader)
    {
        var asm = loader.WinUIReference;
        // CustomAttributesData is the right path for MetadataLoadContext.
        foreach (var attr in asm.GetCustomAttributesData())
        {
            if (attr.AttributeType.FullName == "System.Reflection.AssemblyInformationalVersionAttribute"
                && attr.ConstructorArguments.Count > 0
                && attr.ConstructorArguments[0].Value is string s)
            {
                return s;
            }
        }
        return asm.GetName().Version?.ToString() ?? "(unknown version)";
    }
}
